### PR TITLE
fixed the intro component responsiveness

### PR DESCRIPTION
**Pull request by EngrZaks**
there is still more work to be done on the responsiveness for mobile phones

### CODE REVIEW

**Comment by Maxwell-ihiaso** [comment]
@EngrZaks Please resolve the conflict and push.

You mentioned that there is still more work to be done on responsiveness. This would mean that the MR will be delayed until you confirm that all responsiveness has been handled in line with the PR title.

**Comment by codemuse-io** [comment]
> @EngrZaks Please resolve the conflict and push.
> 
> You mentioned that there is still more work to be done on responsiveness. This would mean that the MR will be delayed until you confirm that all responsiveness has been handled in line with the PR title.

**Comment by codemuse-io** [comment]
> @EngrZaks Please resolve the conflict and push.
> 
> You mentioned that there is still more work to be done on responsiveness. This would mean that the MR will be delayed until you confirm that all responsiveness has been handled in line with the PR title.

@EngrZaks The PR is communicative and approachable, but be sure to resolve the conflicts as @Maxwell-ihiaso mentioned. This file was modified on the previously merged PR.

**Review by codemuse-io — CHANGES_REQUESTED** [review]
@EngrZaks The PR is communicative and approachable, but be sure to resolve the conflicts as @Maxwell-ihiaso mentioned. This file was modified on the previously merged PR.

**Comment by EngrZaks** [comment]
Ok sure

**Comment by codemuse-ke** [comment]
The PR's conflicts appears as not resolved, it's been weeks. I'm gonna close this PR. @EngrZaks You can re-open it once the mergeability is resolved.

**Pull request closed without merging**
