### PR TITLE
Suitable license added

### PR DESCRIPTION
**Pull request by Dorcastunmise**

### CODE REVIEW

**Comment by Dorcastunmise** [comment]
Okay, this is it...I read the readme.md file and noticed the plan for that project is really good and it is not a common application. Now, the GPL license helps protect the **original** work because someone else will want to copy this codes. The GPL License ensures that anyone who uses the software you've created will also have to release any derivative works under an equally free license.

**Comment by Dorcastunmise** [comment]
GPL compels a user to make the source code available when distributing any copies of the software, and that **all modifications** to the original source are also licensed under the GPL.

**Comment by Dorcastunmise** [comment]
the source code-this project's code , will still be included when it get's copied

**Comment by simplytunde** [comment]
100% agreed. Great work @Dorcastunmise

**Review by simplytunde — APPROVED** [review]

**Comment by simplytunde** [comment]
close https://github.com/KanaryStack/aliascheck/issues/35

**Pull request merged**
